// Karma configuration
// Generated on Thu Aug 03 2017 15:01:49 GMT-0400 (Eastern Daylight Time)

const moduleName = 'zedit';

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '..',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
	  'node_modules/angular/angular.js',
	  'node_modules/angular-mocks/angular-mocks.js',
	  'node_modules/angular-ui-router/release/angular-ui-router.js',
	  'node_modules/ui-router-extras/release/ct-ui-router-extras.js',
	  'app/app.js',
	  'app/specs.js.autogenerated'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
	  '**/*.js': ['electron']
    },
	
	
    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['CustomElectron'],
	
	customLaunchers: {
	  CustomElectron: {
		base: 'Electron',
		require: __dirname + '/../app/background.js'
	  }
	},
	
	client: {
	  useIframe: false
	},

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}
